In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

Create a simple dataset

In [2]:
x = np.arange(1, 25).reshape(12, 2)
y = np.array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])
print(x)
print(y)
type(x)
type(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[0 1 1 0 1 0 0 1 1 0 1 0]


numpy.ndarray

Split data with train_test_split

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train

array([[ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16],
       [21, 22],
       [ 7,  8],
       [19, 20],
       [ 9, 10],
       [17, 18]])

In [4]:
x_test

array([[ 1,  2],
       [23, 24],
       [ 3,  4]])

In [5]:
y_train

array([1, 0, 0, 1, 1, 0, 0, 1, 1])

In [6]:
y_test

array([0, 0, 1])

By default, 25 percent of samples are assigned to the test set. 

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=4, random_state=4)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[17 18]
 [ 5  6]
 [23 24]
 [ 1  2]
 [ 3  4]
 [11 12]
 [15 16]
 [21 22]]
[[ 7  8]
 [ 9 10]
 [13 14]
 [19 20]]
[1 1 0 0 1 0 1 1]
[0 1 0 0]


Same as setting test_size=0.33